### PR TITLE
Add Transfer-Encoding: chunked header if no content length is provided

### LINKED ISSUE #39: Consuming "_api/contextinfo" fails due to issue "Http 411 - length required"
Hello Sir,
This is Ruban Joshva again.
When I try uploading files on my SP server(uses NTLM auth), I could not upload the file. When I tried debugging through library I found that, in the file ClientContext.php at line 173 the response is given as "Http 411 - length required" (library trying to consume _api/contextinfo here). But I see the content length is set to 0 in curl.  When I try with one of the other site I am able to get the correct response(content length :0 here too), and able to upload files. When I tried it on REST Client with setting the content length 0, it gives the same response. Why this site is returning this response ? How do I solve this ? Or is there any work around how I can upload the file ?(I am getting issue only when uploading, other functions work fine). And this site(where I face issue) is a SP subsite using NTLM authentication. Thanks.

### PR DESCRIPTION
**Pull request by Deuchnord**
Fix #39.

### CODE REVIEW

**Comment by Deuchnord** [comment]
Why did you close? :astonished:

**Comment by vgrem** [comment]
Sorry, my mistake, just reopened

**Comment by vgrem** [comment]
Looks solid, thanks!

**Comment by Deuchnord** [comment]
Once this PR is merged would it be possible to tag a new minor version with the changes from my last PRs?
Thanks a lot for your reactivity :)

**Comment by vgrem** [comment]
Surely, with the pleasure. Trying my best to merge the last PR via phone from an apartment at Greece island with a pretty poor Internet at the moment.. ;)

**Comment by vgrem** [comment]
Just spotted one minor issue while running unit tests in Travis CI, PHP complain with the warning:

‘array_key_exists() expects parameter 2 to be array, null given in /home/travis/build/vgrem/phpSPO/src/Runtime/Utilities/Requests.php on line 106‘

I assume an additional checking whether headers have been provided would allow to circumvent this warning, something like that:

‘if (is_array($options->Headers) && !array_key_exists('Content-Length', $options->Headers)) {
...
}
‘

**Comment by Deuchnord** [comment]
Nice spot!
I'm creating a new PR to fix this :)

**Comment by vgrem** [comment]
Unfortunately i had to disable this feature for now.
It appears Microsoft Graph service does not support it properly at the moment [Chunked transfer encoding](https://ec.haxx.se/http-response.html) and results in unexpected behavior (such as  empty response from token endpoint).
P.S. Will try to take a look closely and get back to you

**Comment by Deuchnord** [comment]
What do you mean by "disable"? I don't see any commit for that :thinking:

**Comment by vgrem** [comment]
[Here we go](https://github.com/vgrem/phpSPO/commit/6ff0c65bd5902a82c694484b7fd733bf40b7cf3d)

**Comment by vgrem** [comment]
Here are some more details:

For example, this [guy fails](https://github.com/vgrem/phpSPO/blob/2a2a3535da1aa27d1ae39914fb7b65e16e97e791/src/Runtime/Auth/OAuthTokenProvider.php#L78) and returns _empty response_ if Chunked transfer encoding feature enabled:

**Pull request merged**
